# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: services.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservices.proto\x12\x08services\"\x9f\x01\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12!\n\x04role\x18\x04 \x01(\x0e\x32\x13.services.User.Role\"?\n\x04Role\x12\n\n\x06NORMAL\x10\x00\x12\x11\n\rADMINISTRATOR\x10\x01\x12\r\n\tSECRETARY\x10\x02\x12\t\n\x05\x41GENT\x10\x03\"X\n\x0f\x41\x64\x64UserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x1d\n\x05users\x18\x03 \x03(\x0b\x32\x0e.services.User\";\n\x15\x41uthenticationMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\xa2\x01\n\x16\x41uthenticationResponse\x12\x38\n\tuser_role\x18\x01 \x01(\x0e\x32%.services.AuthenticationResponse.Role\x12\r\n\x05token\x18\x02 \x01(\t\"?\n\x04Role\x12\n\n\x06NORMAL\x10\x00\x12\x11\n\rADMINISTRATOR\x10\x01\x12\r\n\tSECRETARY\x10\x02\x12\t\n\x05\x41GENT\x10\x03\x32\xa0\x01\n\x15\x41uthenticationService\x12Q\n\x0c\x41uthenticate\x12\x1f.services.AuthenticationMessage\x1a .services.AuthenticationResponse\x12\x34\n\x07\x41\x64\x64User\x12\x0e.services.User\x1a\x19.services.AddUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=29
  _globals['_USER']._serialized_end=188
  _globals['_USER_ROLE']._serialized_start=125
  _globals['_USER_ROLE']._serialized_end=188
  _globals['_ADDUSERRESPONSE']._serialized_start=190
  _globals['_ADDUSERRESPONSE']._serialized_end=278
  _globals['_AUTHENTICATIONMESSAGE']._serialized_start=280
  _globals['_AUTHENTICATIONMESSAGE']._serialized_end=339
  _globals['_AUTHENTICATIONRESPONSE']._serialized_start=342
  _globals['_AUTHENTICATIONRESPONSE']._serialized_end=504
  _globals['_AUTHENTICATIONRESPONSE_ROLE']._serialized_start=125
  _globals['_AUTHENTICATIONRESPONSE_ROLE']._serialized_end=188
  _globals['_AUTHENTICATIONSERVICE']._serialized_start=507
  _globals['_AUTHENTICATIONSERVICE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
