version: '3.8'

services:
  master:
    build: .
    hostname: master
    command: [
    "mpirun",
    "--hostfile", "/app/hostfile",
    "-np", "5",
    "--mca", "plm_rsh_no_tree_spawn", "1",  
    "--mca", "plm_rsh_agent", "/bin/false", 
    "--allow-run-as-root",                  
    "python3", "ml_service.py"
  ]

    volumes:
      - .:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - MODEL_PATH=/app/fraud_rf_model.pkl
    networks:
      - mpi_network
    depends_on:
      - rabbitmq
      - worker1
      - worker2
      - worker3
      - worker4
      - worker5

  worker1:
    build: .
    hostname: worker1
    command: ["python3", "ml_service.py"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  worker2:
    build: .
    hostname: worker2
    command: ["python3", "ml_service.py"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  worker3:
    build: .
    hostname: worker3
    command: ["python3", "ml_service.py"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  worker4:
    build: .
    hostname: worker4
    command: ["python3", "ml_service.py"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  worker5:
    build: .
    hostname: worker5
    command: ["python3", "ml_service.py"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"  # Advance Message Queuing Protocol (AMQP)
      - "15672:15672"  # Management UI
    networks:
      - mpi_network

networks:
  mpi_network:
    driver: bridge