version: '3.8'

services:
  master:
    build: .
    hostname: master
    ports:
      - "7500:7500"
    command:
      - sh
      - -c
      - |
        # Wait for all dependent services (RabbitMQ, all workers) to be fully up and running.
        sleep 10
        
        # Start ml_service.py with mpirun across all 6 nodes (master + 5 workers) in the background.
        # Added --oversubscribe to allow running more processes than detected slots.
        mpirun --allow-run-as-root --oversubscribe --host master,worker1,worker2,worker3,worker4,worker5 -np 6 /usr/bin/python3 /app/ml_service.py &
        
        # Start the Flask server (main.py) as the primary foreground process for the master container.
        /usr/bin/python3 /app/main.py
    volumes:
      - .:/app
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=7500
      - RABBITMQ_HOST=rabbitmq
      - MODEL_PATH=/app/fraud_rf_model.pkl
    networks:
      - mpi_network
    depends_on:
      - rabbitmq
      - worker1
      - worker2
      - worker3
      - worker4
      - worker5

  worker1:
    build: .
    hostname: worker1
    # Workers just need to be running and available for mpirun to connect to.
    # The sleep command keeps them alive indefinitely.
    command: ["/usr/bin/python3", "-c", "import time; time.sleep(3600)"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  worker2:
    build: .
    hostname: worker2
    command: ["/usr/bin/python3", "-c", "import time; time.sleep(3600)"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  worker3:
    build: .
    hostname: worker3
    command: ["/usr/bin/python3", "-c", "import time; time.sleep(3600)"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  worker4:
    build: .
    hostname: worker4
    command: ["/usr/bin/python3", "-c", "import time; time.sleep(3600)"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  worker5:
    build: .
    hostname: worker5
    command: ["/usr/bin/python3", "-c", "import time; time.sleep(3600)"]
    volumes:
      - .:/app
    networks:
      - mpi_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mpi_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  mpi_network:
    driver: bridge